filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/zeek/*.log
      - /var/log/suricata/eve.json
    json.keys_under_root: true
    json.add_error_key: true

output.kafka:
  hosts: ["kafka:9092"]
  topic: "network-logs"
  codec.json:
    pretty: false

setup.template.enabled: false
